name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      - name: Install dependencies
        run: flutter pub get

      - name: Build code
        run: flutter pub run build_runner build

      - name: Build
        run: flutter build web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: build/web/

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:gerafrequencia --project theahert
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
